### ISSUE TITLE
Non-zero exit code when it should be zero

### ISSUE THREAD

**Issue by edubs5** [mmozuras/pronto#102]
I'm running pronto-rubocop with Gitlab CI.  It's returning a failing exit code even when Pronto is not finding any errors.  Any idea on what is happening?  I can't figure out what that code status means, where does the exit code come from?

    0 Pronto messages posted to GitLab

    ERROR: Build failed with: exit code 36

**Comment by mmozuras** [comment]
@edubs5 are you sure it's coming from Pronto? That seems unlikely.

**Comment by edubs5** [comment]
@mmozuras Thanks, confirmed that it is not related to Pronto.  I looked into it some more, we have a couple different repos and they were not all synced with the main repo's master branch, that's why we got back results that we were not expecting.
