### ISSUE TITLE
pronto doesn't analyse staged changes

### ISSUE THREAD

**Issue by konradstrack** [mmozuras/pronto#111]
I've been trying to execute pronto in a pre-commit hook, and I ended up with the following issue.

Suppose I have a file with inorrect indentation: in this case it's `Gemfile`. I stage it with `git add Gemfile` and execute `pronto run --index`. No issues are reported.

Now, if I do `git reset Gemfile`, `pronto run --index` will report the issues correctly, e.g.:

```
Gemfile:166 I: Inconsistent indentation detected.
Gemfile:167 I: Tab detected.
Gemfile:167 I: Inconsistent indentation detected.
Gemfile:168 I: Tab detected.
Gemfile:168 I: Inconsistent indentation detected.
```

I tested a bit more, and staged changes are not being analysed with all of the following: 
`pronto run`, 
`pronto run --index`, 
`pronto run --commit=$(git log --pretty=format:%H | head -1)`, 
`pronto run --commit=HEAD`.

Is there something trivial I have missed, or is this behaviour expected?

I used Ruby 2.1.5. More info:

```
    pronto (0.5.3)
      gitlab (~> 3.4.0)
      octokit (~> 4.1.0)
      rugged (~> 0.23.0)
      thor (~> 0.19.0)
    pronto-flay (0.5.0)
      flay (~> 2.6.0)
      pronto (~> 0.5.0)
    pronto-jshint (0.5.0)
      jshintrb (~> 0.3.0)
      pronto (~> 0.5.0)
    pronto-rails_best_practices (0.5.0)
      pronto (~> 0.5.0)
      rails_best_practices (~> 1.15.0)
    pronto-rails_schema (0.5.0)
      pronto (~> 0.5.0)
    pronto-rubocop (0.5.0)
      pronto (~> 0.5.0)
      rubocop (~> 0.35.0)
```

**Comment by mmozuras** [comment]
@konradstrack it seems to be a bug introduced in [rugged](https://github.com/libgit2/rugged). I've created an issue [here](https://github.com/mmozuras/pronto/issues/111).

**Comment by mmozuras** [comment]
Changing this from `bug` to `enhancement`. You can follow the discussion here:

https://github.com/libgit2/rugged/issues/548

Will make it part of the next release, because an integration with [overcommit](https://github.com/brigade/overcommit) would be great.

**Comment by elliotthilaire** [comment]
I've also come across this issue.
Is this something I can help with?

**Comment by KirillSuhodolov** [comment]
+ will be great have integration with pronto

**Comment by MvanDiemen** [comment]
@mmozuras any update on how to use this with staged changes?

**Comment by mmozuras** [comment]
@konradstrack @elliotthilaire @KirillSuhodolov @MvanDiemen I've renamed the `--index` option to `--unstaged` and added `--staged` options as requested with [this commit](https://github.com/mmozuras/pronto/commit/818ba1be68a6797158d22e148cff282d12a70db2). You can test it by building master and installing master locally. Would love feedback 😄

**Comment by MvanDiemen** [comment]
```
~/r/nfr:cleanup/introduce-pronto> bundle show pronto
/home/michael/.gem/ruby/2.3.1/bundler/gems/pronto-037afde01882
~/r/nfr:cleanup/introduce-pronto> git diff app
diff --git a/app/controllers/backend/contracts_controller.rb b/app/controllers/backend/contracts_controller.rb
index 48c55a963..cdf793393 100644
--- a/app/controllers/backend/contracts_controller.rb
+++ b/app/controllers/backend/contracts_controller.rb
@@ -71,6 +71,10 @@ class Backend::ContractsController < InheritedResources::Base
     render
   end
 
+  def ThisMethodFails
+    'foo' == true ? true == false ? raise StandardError, "Foo" : nil : nil
+  end
+
   def export_to_excel_bang
 
~/r/nfr:cleanup/introduce-pronto> bundle exec pronto run --unstaged
app/controllers/backend/contracts_controller.rb:75 E: dynamic constant assignment
(Using Ruby 2.3 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)
app/controllers/backend/contracts_controller.rb:75 E: unexpected token tCONSTANT
(Using Ruby 2.3 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)
~/r/nfr:cleanup/introduce-pronto> git add app
~/r/nfr:cleanup/introduce-pronto> git diff --cached app
diff --git a/app/controllers/backend/contracts_controller.rb b/app/controllers/backend/contracts_controller.rb
index 48c55a963..cdf793393 100644
--- a/app/controllers/backend/contracts_controller.rb
+++ b/app/controllers/backend/contracts_controller.rb
@@ -71,6 +71,10 @@ class Backend::ContractsController < InheritedResources::Base
     render
   end
 
+  def ThisMethodFails
+    'foo' == true ? true == false ? raise StandardError, "Foo" : nil : nil
+  end
+
   def export_to_excel_bang
 
~/r/nfr:cleanup/introduce-pronto> bundle exec pronto run --staged
```

I am using the current master branch but it's still not showing the errors for staged changes.

**Comment by mmozuras** [comment]
@KirillSuhodolov @glennr you can find the PR on Overcommit for a pre-commit hook here: https://github.com/brigade/overcommit/pull/488
