### ISSUE TITLE
Provide the adequate runner class in a message

### ISSUE THREAD

**Issue by skateman** [mmozuras/pronto#113]
Hi!

I need to have the runner class name inside each report message for a personal project. The simplest solution is to add an extra runner argument to the constructor of the `Message` class, but this requires to adjust all the existing runners. An other (very ugly) solution is to somehow [parse the backtrace](https://github.com/kami-zh/caller_class) in the `Message`'s constructor and get the caller class from it. 

Which solution sounds better for you? Would you accept a PR?

**Comment by mmozuras** [comment]
> The simplest solution is to add an extra runner argument to the constructor of the Message class, but this requires to adjust all the existing runners.

I think that's the way to go and I would accept a PR :smile:.

**Comment by dwradcliffe** [comment]
I need this also. Any progress?

**Comment by skateman** [comment]
Umm, holidays :) I'll do it tomorrow ;)

**Comment by dwradcliffe** [comment]
Awesome :)
