### ISSUE TITLE
Runner Issues

### ISSUE THREAD

**Issue by Schwad** [mmozuras/pronto#114]
Following runners dependant on older versions of pronto so cannot run them in whole package with latest pronto. Included are links to relevant files.

[pronto/reek](https://github.com/mmozuras/pronto-reek/blob/master/pronto-reek.gemspec)
[pronto/spell](https://github.com/mmozuras/pronto-spell/blob/master/pronto-spell.gemspec)
[pronto/fasterer](https://github.com/mmozuras/pronto-fasterer/blob/master/pronto-fasterer.gemspec)

I found this including the gems in the following format in my gemfile

```
gem 'pronto'
gem 'pronto-fasterer', require: false
gem 'pronto-spell', require: false 
gem 'pronto-reek', require: false 
```

Other runners are running just fine. 

If there's anything integration-wise I'm missing just give me a holler!

**Comment by mmozuras** [comment]
@Schwad when releasing newest version of Pronto, I missed `spell` and `fasterer`, failing to make them compatible with 0.5.0 :bow:.

Done now and released :smile:.

**Comment by Schwad** [comment]
Sweet! Glad to know I wasn't crazy, will be adding those runners to my application now, thanks! :D :+1:
