### ISSUE TITLE
Can't install on JRuby due to C Extensions dependency

### ISSUE THREAD

**Issue by eprislac** [mmozuras/pronto#118]
Any possibility of dropping the dependency on rugged in favor of a pure-ruby Git library?

**Comment by mmozuras** [comment]
@eprislac I have no intention to work on it myself. But I would accept contributions, if performance is not significantly negatively impacted.

**Comment by eprislac** [comment]
@mmozuras the projects I currently work on use JRuby exclusively, with no hope of switching. I'm going to try running pronto on PRs from a different ruby, but may end up forking this to use a different Git library if I can't get that working. Thanks for the response!

**Comment by zoras** [comment]
@eprislac RJGit seems to be the alternative for rugged in jruby
https://github.com/repotag/rjgit

**Comment by volkanunsal** [comment]
There is also [ruby-git](https://github.com/ruby-git/ruby-git). Rather than using a system library, it uses the git CLI interface to communicate with Git.
