### ISSUE TITLE
Timeout option

### ISSUE THREAD

**Issue by bigtunacan** [mmozuras/pronto#120]
It would be great if there was an option to pass a timeout that would cause Pronto to automatically quit after a specified time.

I found times where running pronto will run for hours before completing when there is a large enough delta between the specified commit and HEAD.  I use this in an automated build/test suite on Jenkins to do code analysis of recent change, but then the entire test suite ends up being held up.

**Comment by mmozuras** [comment]
@bigtunacan have you considered using [timeout](http://man7.org/linux/man-pages/man1/timeout.1.html) from [coreutils](http://www.gnu.org/software/coreutils/coreutils.html)? Can be installed on Mac with [homebrew](https://github.com/Homebrew/homebrew).

> I found times where running pronto will run for hours before completing when there is a large enough delta between the specified commit and HEAD.

Could you give me more info when these situations happen? Just want to understand if that's possible to avoid :smile:

**Comment by mmozuras** [comment]
@bigtunacan ping :smile:

**Comment by bigtunacan** [comment]
@mmozuras Sorry; somehow I missed the notification on this originally.  I'll take a look at that as an option.  Thanks.

**Comment by mmozuras** [comment]
I think that it's not something that should be solved in `pronto`.

Feel free to reopen, if you have a different opinion 😄

**Comment by bigtunacan** [comment]
@mmozuras no worries the timeout option you suggested works fine I'm using that.  Sorry I didn't update the issue.
