### ISSUE TITLE
GitHub status formatter

### ISSUE THREAD

**Issue by dwradcliffe** [mmozuras/pronto#121]
It would be really great if we could add custom statuses to a GitHub PR, one for each runner. This would make it much easier to see what failed at a glance, instead of lumping everything into one status.

I've started looking at the code to see what needs to change to make this happen.

This would depend on #113 and #83

**Comment by dwradcliffe** [comment]
Here's an example:

![wip pronto by dwradcliffe](https://cloud.githubusercontent.com/assets/118850/12099473/bbb98164-b2f6-11e5-9fb6-871258cf1a6d.png)

**Comment by mmozuras** [comment]
@dwradcliffe good idea!

Without making any changes, today this can be achieved by running Pronto multiple times, each time specifying a single runner. Not ideal, I know :smile:

**Comment by dwradcliffe** [comment]
Yep, that was my plan until #83 is done. Still need #113 for my implementation to work.

**Comment by mknapik** [comment]
What is the status of this enhancement?

**Comment by mknapik** [comment]
@mmozuras @dwradcliffe I'm willing to submit PR if nobody has started working on this feature.

**Comment by mmozuras** [comment]
@mknapik I haven't started working on it 😄
