### ISSUE TITLE
ESLint Support Desired

### ISSUE THREAD

**Issue by tscheffe** [mmozuras/pronto#128]
I'm looking for a `pronto-eslint`. I see that there's a [pronto-jshint](https://github.com/mmozuras/pronto-jshint), I imagine that it wouldn't be too much difference.

I'd like to get `eslint` into the `pronto` ecosystem so the tools I'm building with it are compatible with both the front and backend projects at my workplace.

**Comment by mmozuras** [comment]
@tscheffe will have this feature request in mind. Do tell if you'll decide to implement it yourself :smile:

**Comment by mmozuras** [comment]
Done: https://github.com/mmozuras/pronto-eslint :smile:

**Comment by dankohn** [comment]
Awesome! Thank you.

--
Dan Kohn <mailto:dan@dankohn.com>
tel:+1-415-233-1000

**Comment by tscheffe** [comment]
:+1: :smile: :+1: :smile: :+1: :smile_cat:
