### ISSUE TITLE
Text Formatter with Color

### ISSUE THREAD

**Issue by tscheffe** [mmozuras/pronto#129]
Currently the text formatter doesn't output in color but it would look much nicer if it did.

Given the standard (--colored) config, would that be an acceptable feature?

The way [Rubocop does it](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/formatter/simple_text_formatter.rb) using [Rainbow](https://github.com/sickill/rainbow) seems like a good pattern to follow, it wouldn't be that complex.

**Comment by mmozuras** [comment]
:+1:, sounds like a great idea, would accept a PR for it!

**Comment by tscheffe** [comment]
:+1: I'm super interested so I'm tentatively planning to take a stab at it sometime.

**Comment by nbekirov** [comment]
@mmozuras, @tscheffe Is anyone currently working on this? I've started playing around and have some progress that can easily be turned into a PR if you don't mind. :)

**Comment by tscheffe** [comment]
I haven't been. Though I would love to see a PR!

I'd be glad to review it and provide feedback if you open one!

**Comment by nbekirov** [comment]
@tscheffe Thanks! 

I'll ping you when the PR is ready. :smile:

**Comment by nbekirov** [comment]
@mmozuras @tscheffe 

Please give me some feedback on the PR I've made! :sleepy:
