### ISSUE TITLE
running pronto fails with ruby 2.3.0

### ISSUE THREAD

**Issue by donni106** [mmozuras/pronto#132]
No problems running pronto with older ruby versions.
When trying to run pronto in ruby 2.3.0 project, it fails with:

.../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc6b54aa8d8 pronto-0.6.0> (NoMethodError)
	from ...rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from .../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from .../.rvm/gems/ruby-2.3.0@vitality-backend/gems/pronto-0.6.0/bin/pronto:3:in `<top (required)>'
	from .../.rvm/gems/ruby-2.3.0@vitality-backend/bin/pronto:23:in `load'
	from .../.rvm/gems/ruby-2.3.0@vitality-backend/bin/pronto:23:in `<main>'
	from .../.rvm/gems/ruby-2.3.0@vitality-backend/bin/ruby_executable_hooks:15:in `eval'
	from .../.rvm/gems/ruby-2.3.0@vitality-backend/bin/ruby_executable_hooks:15:in `<main>

Any suggestions?

**Comment by donni106** [comment]
https://github.com/remomueller/documentation/issues/7 this issues the same error and the result is to downgrade rubygems

**Comment by mmozuras** [comment]
@donni106 thanks for reporting, as it's not a `pronto` issue, closing it 😄

**Comment by Fabs** [comment]
I got the same error because of `rails_best_practices`. Once I took pronto away of my Gemfile (because it was conflicting with other dependencies I have), then it stop working from my environment because of `pronto-rails_best_practtices`. When I remove this runner everything was well.

**Comment by mmozuras** [comment]
@Fabs have you tried updating rubygems by running `gem update --system` (reference: https://github.com/railsbp/rails_best_practices/issues/279)
