### ISSUE TITLE
Integration with Bitbucket Server (formerly Atlassian Stash)

### ISSUE THREAD

**Issue by tubbo** [mmozuras/pronto#140]
I noticed that there's an integration for cloud-hosted Bitbucket, but what about Bitbucket Server (formerly Stash)? My company uses Stash, and it seems like if we can get things working this tool will be very helpful for our code review process. Has there been any work done on this prior to now so I can take a look? I have [a branch going on my fork](https://github.com/tubbo/pronto/tree/bitbucket-server-integration) that is a good start to getting Bitbucket Server integrated with Pronto, but also wondering if anyone else might need this?

**Comment by mmozuras** [comment]
@tubbo does Bitbucket server requires a separate integration or can just the bitbucket `web_endpoint` be changed in config?

**Comment by tubbo** [comment]
I've been looking it over the last few days and it seems like the Stash API is just different enough from the Bitbucket API to make this not work. Tried running it with my own username and password but couldn't get it to post any comments.

**Comment by jwarlander** [comment]
Definitely interested in this; @tubbo, were you able to get it working in your branch?

**Comment by tubbo** [comment]
I wasn't able to just yet, but I think I'm having some local access issues. Will report back when I get it tested correctly.

**Comment by dstull** [comment]
interested in bitbucket server working as well against pull requests.  I believe this code will prevent it due to base setting...

https://github.com/mmozuras/pronto/blob/master/lib/pronto/clients/bitbucket_client.rb#L26

**Comment by andrey-skat** [comment]
There are different APIs for cloud and server versions

https://developer.atlassian.com/bitbucket/api/2/reference/resource/
https://developer.atlassian.com/static/rest/bitbucket-server/latest/bitbucket-rest.html

**Comment by andrey-skat** [comment]
I added pr with formatter #216

**Comment by mmozuras** [comment]
Resolved with #216, will be released in the next version - `0.9.0`.

**Comment by mmozuras** [comment]
Released [v0.9.0](https://github.com/mmozuras/pronto/releases/tag/v0.9.0) with `bitbucket_server_pr` as an option.
