### ISSUE TITLE
Gitlab slug should be gitlab id and not repo/project

### ISSUE THREAD

**Issue by kt0** [mmozuras/pronto#146]
In the example config for gitlab in README it uses `repo/project` style, we did just like that and gitlab was raising 500 error (it was actually 404 in the Gitlab logs!), after reading Gitlab api docs it seems that it should be [project id](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/commits.md#post-comment-to-commit) (and it's absolutely hard to figure out what is the id of a project, I've got the id with manually getting list of projects with curl calling Gitlab APIs).

**Comment by mmozuras** [comment]
@kt0 so, it's an issue with our documentation, right? Or is there an alternative we could use?

**Comment by kt0** [comment]
@mmozuras I think it's an issue with documentation, we have used `user/repo` in slug, and didn't work, after changing it to project_id worked with no errors.

**Comment by mmozuras** [comment]
@kt0 I've changed the example in README. That (and existence of this issue) should be enough to help prevent future problems 😄 

Thanks! 🙇 👍
