### ISSUE TITLE
Is there any way to combine errors of same line in one comment?

### ISSUE THREAD

**Issue by kt0** [mmozuras/pronto#147]
Currently pronto creates a comment for each error, even if all those errors are on the same line, it'll be nice if those comments combined together as just one comment.

P.S. I've read the `Pronto::Formatters:: GitlabFormatter` code and it seems if we split commit message by line (or maybe bullet points) we can get the result fairly easy, if it's ok I can make a pull request for it.

P.S 2 IDK about github part and not sure it's possible there or not!

**Comment by mmozuras** [comment]
@kt0 sounds like a good idea 👍. I think that it should be an option for all GitHub/GitLab/Bitbucket formatters.

**Comment by doomspork** [comment]
Hi @kt0 and @mmozuras, I recently did this on my own fork and was going to see if anyone else was interested:  https://github.com/doomspork/pronto/tree/consolidated-messaging

When there are multiple comments I combine them into one and add checkboxes but I'm open to whatever.  Let me know what you think and I can open a PR.

Here it is in action:

![image](https://cloud.githubusercontent.com/assets/73386/15087942/932d78d8-13a2-11e6-955a-54a567106031.png)

**Comment by mmozuras** [comment]
@doomspork looks good, except not sure about checkboxes. How do you expect them to be used?

**Comment by doomspork** [comment]
Howdy @mmozuras, no goal with the checkboxes at the moment.  I'm playing with better ways to display the multiple issues.  Just listing them in order wasn't very clear IMO:

```text
Calls @user.errors 2 times (DuplicateMethodCall)
Calls format.json 4 times (DuplicateMethodCall)
Calls format.json { render json: @user.errors, status: :unprocessable_entity } 2 times (DuplicateMethodCall)
Calls render json: @user.errors, status: :unprocessable_entity 2 times (DuplicateMethodCall)
```

I'd like to use a list of some sort so there is delineation between feedback, checkboxes were my most recent test 😀

**Comment by doomspork** [comment]
@kt0 I've opened a pull request with my current implementation, your feedback is welcomed 😀

**Comment by steverob** [comment]
@mmozuras can this be closed? :)

**Comment by mmozuras** [comment]
@steverob yes, it can! 😄
