### ISSUE TITLE
Don't see any status on Github

### ISSUE THREAD

**Issue by bolom** [mmozuras/pronto#155]
Hi

I have build a small CI who allow me to review my PR from a swift and ios projects. 

https://github.com/LoboBot/heart

I don't see any status pushed on Github

https://github.com/LordAlexWorks/proactives/pull/1163

My script

https://github.com/LoboBot/heart/blob/master/review_pr.sh

Should i do something wrong ?

B

**Comment by mmozuras** [comment]
@bolom which version of Pronto `0.6.0` are you using? `github_status` is currently available only on `master` (will be released soon).

**Comment by mmozuras** [comment]
@mknapik consolidation (#154) is the last bigger feature I'll wait to be completed before a release 😄 
Might be as early as next week, but it's not a promise 😄

**Comment by mknapik** [comment]
Good luck then :-)

**Comment by mmozuras** [comment]
Done 😄
