### ISSUE TITLE
github_status - any way to add details link?

### ISSUE THREAD

**Issue by edk** [mmozuras/pronto#158]
when using the new github_status formatter, it lists the number of warnings and fatal in the status, but without a details link:
` pronto/rubocop — Found 6 infos and 1 fatal.`

Is there a way to pass the url via param or ENV variable so that can be added?

**Comment by mmozuras** [comment]
GitHub does provide a way to do it via their API: https://developer.github.com/v3/repos/statuses/

@edk where could it lead to? CI job status page?

/cc @mknapik

**Comment by mknapik** [comment]
My understanding is that `GithubStatusFormatter` is used together with `GithubPullRequestFormatter` so the comments are already in the PR.

**Comment by edk** [comment]
k, will investigate.  thanks!

**Comment by mknapik** [comment]
@edk Do you wish to have different URL for each pronto plugin?
