### ISSUE TITLE
pronto-flay-0.6.1/lib/pronto/flay.rb:8:in `run': undefined method `filter_files' for Flay:Class

### ISSUE THREAD

**Issue by hovancik** [mmozuras/pronto#161]
Hi there, 

I recently run `bundle update` on one project and I am getting error when running `pronto run`

You can see full error here: https://travis-ci.org/DiscoverBSD/talks/jobs/138590329
PR is here: https://github.com/DiscoverBSD/talks/pull/33

**Comment by mmozuras** [comment]
@hovancik thanks for reporting 👍 

Should be fixed by https://github.com/mmozuras/pronto-flay/pull/11.

/cc @abinoam

**Comment by hovancik** [comment]
@abinoam @mmozuras any news? No changes in there for 12 days

**Comment by mmozuras** [comment]
@hovancik sorry, sometimes it takes for a while to get to reviewing everything 😄  

Merged and released! Please re-open if the issue still persists
