### ISSUE TITLE
Overriding configurations / Inject Access token

### ISSUE THREAD

**Issue by steverob** [mmozuras/pronto#166]
I have my GitHub access token & slug in the database. Is there a way to inject these configurations into the gem when it is initializing `Github` object?

**Comment by mmozuras** [comment]
@steverob 

There are multiple ways to configure the access token for Pronto:
https://github.com/mmozuras/pronto#github-integration

@steverob you should never need to configure the slug. Could you expand on what you're trying to achieve? 😄

**Comment by steverob** [comment]
@mmozuras Yeah you're right, I dont need to configure slug. Thanks @mmozuras :)

**Comment by steverob** [comment]
@mmozuras I was trying to automate setting up pronto by making it a service for my company folks :)
