### ISSUE TITLE
README says "integrates with GitLab and Bitbucket", forgot Github

### ISSUE THREAD

**Issue by Fernan2** [mmozuras/pronto#176]
README says "integrates with GitLab and Bitbucket":
![captura de pantalla 2016-09-14 a la s 20 20 50](https://cloud.githubusercontent.com/assets/103583/18524474/c9679e24-7ab8-11e6-9d2d-b7da99f01386.png)

Only later you see that it also integrates with Github:
![captura de pantalla 2016-09-14 a la s 20 22 15](https://cloud.githubusercontent.com/assets/103583/18524513/f715c5b2-7ab8-11e6-9d7f-276a3b26d21c.png)

**Comment by mmozuras** [comment]
@Fernan2 thanks for pointing that out! 🙇
