### ISSUE TITLE
Pronto spam my pull request with the last version of github

### ISSUE THREAD

**Issue by benoittgt** [mmozuras/pronto#177]
Hello

First thanks for pronto. We love it. We are using it as a task with jenkins with something like : 
```sh
bundle exec pronto run -f github_pr -c origin/develop
```
It was working good since the last update of github. Now we get this : 
<img width="342" alt="capture d ecran 2016-09-16 a 15 26 41" src="https://cloud.githubusercontent.com/assets/8417720/18587373/fd963844-7c21-11e6-8f5a-6fc63089caee.png">

I tried to run the command locally and didn't get all this message. Do you have any idea of what can happen?

Thanks

**Comment by ibrahima** [comment]
It'll be nice if Github opens up the API for pull request reviews so that Pronto can just post a single review with all the comments rather than commenting multiple times. I guess that's what causes this issue? Seems like it's completely on github to fix though.

**Comment by benoittgt** [comment]
Yes @ibrahima. I've sent an email to github at the same time I opened this issue. They fowarded my mail to eng team. No answer for the moment

**Comment by ibrahima** [comment]
Here's a link to the platform forum thread about the PR Review API: https://platform.github.community/t/api-endpoint-for-pr-reviews/409/2

Hopefully they add it soon, but it's not on their roadmap yet :(

**Comment by benoittgt** [comment]
It seems in jenkins it fails to post 

```
Failed to post: [9b862728ae6f85ba2d8cd70a3499056521381171] Gemfile:34
- Prefer single-quoted strings when you don't need string
interpolation or special symbols. with POST
https://api.github.com/repos/appaloosa-store/appaloosa/pulls/308/comments:
422 - Validation Failed
Error summary:
  resource: PullRequestReviewComment
  code: invalid
  field: position // See:
https://developer.github.com/v3/pulls/comments/#create-a-comment
Failed to post: [9b862728ae6f85ba2d8cd70a3499056521381171] Gemfile:34
- Line is too long. [141/120] with POST
https://api.github.com/repos/appaloosa-store/appaloosa/pulls/308/comments:
422 - Validation Failed
Error summary:
  resource: PullRequestReviewComment
  code: invalid
  field: position // See:
...
```

**Comment by mpluta-airhelp** [comment]
Can we make pronto fallback on older version of the API? Waiting for GH to open their review API seems like a long time... I think we actually used this trick on our TeamCity instance for pushing status updates to GH. But GH plugin for TC is not impacting pronto calls.

**Comment by ibrahima** [comment]
I don't think pronto is using any different API than before, it's just
Github that started displaying things differently.

**Comment by mpluta-airhelp** [comment]
Yesterday sth changed. For couple of days no pronto comments were visible on PR and now thay appear in form of review. Everything nice but... They are not being updated after fix is aplied, nor can you remove them manually. Is GH changing sth...?

**Comment by benoittgt** [comment]
Maybe it's related to the mail I sent to them. Will give a try today.

**Comment by benoittgt** [comment]
No more noise but new API seems still unaccessible with the same message as before : https://github.com/mmozuras/pronto/issues/177#issuecomment-248917616

**Comment by benoittgt** [comment]
Ok I just received a proper published comment on a PR. Closing the issue, because it's resolve for me.

**Comment by mmozuras** [comment]
@benoittgt thanks! 🙇

**Comment by ibrahima** [comment]
https://developer.github.com/changes/2016-12-14-reviews-api/ new API is now available, though not yet supported by Octokit.
