### ISSUE TITLE
Suppress some Pronto runners from posting Github commit statuses

### ISSUE THREAD

**Issue by ibrahima** [mmozuras/pronto#178]
I really like the new Github status feature, but it'd be nice if you could suppress some Pronto runners from posting Github commit statuses. For instance, we have a bunch of runners, some of which are more important than others, and it'd be nice for us to know that there are no Rubocop violations, but we don't care as much about others to include them in the statuses list. Or alternatively, it'd be nice to be able to collapse the ones that are "less important" into one status.

I might submit a PR for this myself if I have time. How should the configuration for this look? Should we have a list of "status-generating" runners, or perhaps just "important" runners, and then the rest can be collapsed into one status? That seems like a reasonable set of options to me. Any thoughts?

**Comment by mmozuras** [comment]
I think that two configuration options make sense:

* ability to override `DEFAULT_LEVEL_TO_STATE_MAPPING` for each runner.
* ability to specify which runners deserve a status.

Not sure if we need the ability to collapse the rest into one status. That seems a little much. But I might've not encountered the scenario that would require it. How many runners do you currently use?

**Comment by ibrahima** [comment]
As a followup, I realized later that there's a pretty obvious workaround for those running Pronto in CI. Just run some subset of runners with the commit status formatter, and some without, and you'll get the desired result. We have about 9-10 runners and some of them are less "blocker"y than others, at least for our team.
