### ISSUE TITLE
pronto-brakeman and pronto-rails_best_practices not playing nicely with each other

### ISSUE THREAD

**Issue by prpetten** [mmozuras/pronto#180]
When `pronto-brakeman` is included with `pronto-rails_best_practices`, `pronto-rails_best_practices` is unable to find any violations it finds when `pronto-brakeman` isn't present. Interestingly `pronto-brakeman` does not appear to bother any other `pronto` runners, at least not the ones I'm using.  I confirmed it was `pronto-brakeman` that was causing the issue with `pronto-rails_best_practices`.

Here is my setup
```ruby
# Gemfile
group :development do
  gem 'pronto',                      '~> 0.7',  require: false     # Runs analysis by checking only the relevant changes
  gem 'pronto-brakeman',             '~> 0.7',  require: false     # Runs brakeman through pronto
  gem 'pronto-fasterer',             '~> 0.7',  require: false     # Runs fasterer through pronto
  gem 'pronto-flay',                 '~> 0.7',  require: false     # Runs flay through pronto
  gem 'pronto-rails_best_practices', '~> 0.7',  require: false     # Runs rails_best_practices through pronto
  gem 'pronto-reek',                 '~> 0.7',  require: false     # Runs reek through pronto
  gem 'pronto-rubocop',              '~> 0.7',  require: false     # Runs rubocop through pronto
end
```

```yaml
# .pronto.yml
all:
  exclude:
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
max_warnings: 150
github:
  slug: owner/repo
```

With both `pronto-brakeman` and `pronto-rails_best_practices`  with my comments on which runner is creating each violation
```shell
$ pronto run -c origin/develop
app/controllers/pronto_controller.rb:8 F: Possible security vuln...  # pronto-brakeman
app/proto/test_wrapper.rb:14 W: Using each_with_index is slower...   # pronto-fasterer
app/controllers/pronto_controller.rb:12 W: Similar code found in ... # pronto-flay
app/controllers/pronto_controller.rb:1 I: Has no descriptive comm... # pronto-reek
app/proto/test_wrapper.rb:8 I: Use `&&` instead of `and`.            # pronto-rubocop
```
Now without `pronto-brakeman` in `Gemfile`
```shell
$ pronto run -c origin/develop
app/proto/test_wrapper.rb:14 W: Using each_with_index is slower...   # pronto-fasterer
app/controllers/pronto_controller.rb:12 W: Similar code found in ... # pronto-flay
app/controllers/pronto_controller.rb:2 W: Remove unused methods...   # pronto-rails_best_practices
app/controllers/pronto_controller.rb:1 I: Has no descriptive comm... # pronto-reek
app/proto/test_wrapper.rb:8 I: Use `&&` instead of `and`.            # pronto-rubocop
```

Interestingly, when I ran the `pronto` gem locally reversing the order of the runners execution with the following change:
```ruby
# lib/pronto/runners.rb
module Pronto
  class Runners
    def initialize(runners = Runner.runners, config = Config.new)
      # @runners = runners  -- Original Line
      @runners = runners.reverse!  # My new line
      @config = config
    end
  end
end
```
I was able to get both `pronto-brakeman` and `pronto-rails_best_practices` to create violations, as shown below.
```shell
$ pronto run -c origin/develop
app/proto/test_wrapper.rb:8 I: Use `&&` instead of `and`.            # pronto-rubocop
app/controllers/pronto_controller.rb:1 I: Has no descriptive comm... # pronto-reek
app/controllers/pronto_controller.rb:2 W: Remove unused methods...   # pronto-rails_best_practices
app/controllers/pronto_controller.rb:12 W: Similar code found in ... # pronto-flay
app/proto/test_wrapper.rb:14 W: Using each_with_index is slower...   # pronto-fasterer
app/controllers/pronto_controller.rb:8 F: Possible security vuln...  # pronto-brakeman
```

So it appears that there is something that `pronto-brakeman` is doing that doesn't affect the other runners, but does affect `pronto-rails_best_practices` for some reason.  I tried figuring out a fix, but there doesn't appear to be anything noticeably different between the other runners and either `pronto-brakeman` or `pronto-rails_best_practices`.

See referenced issues on `pronto-brakeman` and `pronto-rails_best_practices` as well:
mmozuras/pronto-brakeman#11
mmozuras/pronto-rails_best_practices#4

**Comment by nbekirov** [comment]
Is this related to #80?

**Comment by prpetten** [comment]
<embarassed> Yes, I can't believe I missed that, I could have sworn I read them all, and its right there in the title.  Feel free to mark as a duplicate and close.

**Comment by prpetten** [comment]
@nbekirov it certainly appears so.  Feel free to close as duplicate, I could have sworn I looked through the issues, but
