### ISSUE TITLE
GitHub Pull Request formatter fails if comments already exist

### ISSUE THREAD

**Issue by mknapik** [mmozuras/pronto#188]
I got the following error on my CI:
```
/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/lib/pronto/github.rb:35:in `create_pull_comment': undefined method `body' for nil:NilClass (NoMethodError)
```

After some debugging it turned out the error occurred for already existing comments.
Further troubleshooting showed it might have been related to `consolidate_comments` option.
I've created example project with 2 pull request:
* mknapik/pronto-github-nil-comment-issue#1 fails on second Pronto run
* mknapik/pronto-github-nil-comment-issue#2 works fine

The only difference is PR1 uses [comments consolidation](https://github.com/mknapik/pronto-github-nil-comment-issue/pull/1/commits/97873954574da44f0ea0f1dea8a02cc98d4d8eb5).
`GitFormatter#remove_duplicate_comments` returns `nil` for each commit which is already present.

CC: @doomspork

**Comment by doomspork** [comment]
@mknapik I'll take a peek at this later today but I can't say I've run into this myself and we've been using the consolidated comments since before they were merged into Pronto.

**Comment by doomspork** [comment]
@mknapik were the comments existing _before_ you ran Pronto?  Were they from a previous run?

**Comment by mknapik** [comment]
@doomspork Yes, from previous pronto run.
