### ISSUE TITLE
Support message prefixes

### ISSUE THREAD

**Issue by christhekeele** [mmozuras/pronto#192]
It'd be nice to be able to configure `pronto` to prepend prefixes to the messages it creates.

The usecase I have in mind is: since it posts as a user to git hosting sites, it'd be nice to annotate the comments it leaves with `"Automated style linter:\n"` or some such thing.

Most linters have... assertive messages like "Prefer doing xxx", or "You must do yyy", and I've been put off from continuing work on pull requests before waking up to a flood of comments on a PR with stylistic demands issued by an actual human being. I'd hate to automate the same experience on projects that I own.

I can think of other ways this might be useful, but that's the most compelling case.

`Pronto::Message` could just look for `PRONTO_MESSAGE_PREFIX` configuration on initialization, I think.

**Comment by mmozuras** [comment]
@christhekeele have you considered having a separate user for Pronto? That's how we solve this issue - with a separate bot user, who's clearly recognised as such.

I would accept a PR for this enhancement, if someone would write it.

**Comment by mmozuras** [comment]
Will be solved by this PR: https://github.com/mmozuras/pronto/pull/204
