### ISSUE TITLE
Confusion around `--index` option

### ISSUE THREAD

**Issue by tscheffe** [mmozuras/pronto#193]
Recently had some confusion with the `--index` option.

Expected:
`Run on the diff between master and HEAD, _including staged changes_`

Actual:
`Run on _only_ on the diff between master and staged changes, not including committed changes`

The issue then, is my `Actual` interpretation correct? If so, would a PR from me attempting to clean up the README documentation and examples be accepted?

I do think the the implementation I discovered makes sense, after all I can just run it again without the `--index`. I just wish I had understood what it did from the get-go.

**Comment by mmozuras** [comment]
@tscheffe yes, I think that your `Actual` interpretation is correct. And, of course, I would accept any PR that improves documentation 😄 

Reference: [original issue](https://github.com/mmozuras/pronto/pull/40/files). /cc @splattael

**Comment by splattael** [comment]
I'm with @tscheffe. I would have expected the `Expected` too before I contributed `--index`.
But making this the default behaviour might surprise other users and possibly break their CI.

:+1: for better doco :green_heart:

**Comment by dgmora** [comment]
I've also been bitten by this. There are a couple of mentions in the readme:

This is correct, but kind of confusing because it doesn't check the index, but the diff between index and current directory:
```
# Analyze diff of uncommitted changes and master:
pronto run --index
```
Just not correct (Also in  `pronto help run`):
```
-i/--index	Analyze changes in git index (staging area).
```

For me the current behavior should be called `unstaged`, as...it checks the files that have not been yet staged for commit, and `--index` option should check the files in the index. Just my two cents 🙂

**Comment by mmozuras** [comment]
@tscheffe @splattael @dgmora I've renamed the `--index` option to `--unstaged` and added `--staged` options as requested by #111 with [this commit](https://github.com/mmozuras/pronto/commit/818ba1be68a6797158d22e148cff282d12a70db2). Would love to hear some feedback 😄

**Comment by splattael** [comment]
@mmozuras This is a very nice solution! Like it. Thank you :+1:

**Comment by tscheffe** [comment]
They changes look fantastic!
