### ISSUE TITLE
Messages with nil line crash pronto

### ISSUE THREAD

**Issue by npetkov** [mmozuras/pronto#201]
I'm using `pronto 0.7.1` & company. I've stumbled upon this exception:

    NoMethodError: undefined method `new_lineno' for nil:NilClass /.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.7.1/lib/pronto/formatter/github_pull_request_formatter.rb:13:in `line_number'

Checking the code it's obvious that `line_number` in `GithubPullRequestFormatter ` expects non-`nil` value for line.

As it turned out, `pronto-poper` creates the following message:

    #<Pronto::Message:0x007fd7ea4c7df8 @path=nil, @line=nil, @level=:warning, @msg="Git commit message should start with a capital letter", @runner=Pronto::Poper, @commit_sha="b2c4d4563e3b2e57ece14faa9067cec3eb68b193">

Clearly, this is by design so it's not a `poper` issue per se, rather it's the way pronto itself handles such messages.

**Comment by mmozuras** [comment]
Released a fix with [v0.8.1](https://github.com/mmozuras/pronto/releases/tag/v0.8.1).
