### ISSUE TITLE
Cut a new version soon?

### ISSUE THREAD

**Issue by david-a-wheeler** [mmozuras/pronto#202]
Hi - love pronto.  But the current release (0.7.1) depends httparty - and an extremely specific version of it (~> 0.13.7), and this causes many other dependencies in my system to be stuck.  I see that commit 82d195cb461b6abd1f8f72755c6116feb78077d3 fixes this.  Can you release new version of pronto sooner?  Yes, I could depend on an untagged version, but I'd rather use a "release" version since that suggests some confidence in the result.

Thanks!

**Comment by mmozuras** [comment]
@david-a-wheeler done! 👍 
https://github.com/mmozuras/pronto/releases/tag/v0.8.0

**Comment by david-a-wheeler** [comment]
Awesome! Thanks!
