### ISSUE TITLE
Message format

### ISSUE THREAD

**Issue by romulomourao** [mmozuras/pronto#209]
Hi. 
I've been trying to use the format option in the .pronto.yml file but it seems not to work

```
format: "%{runner} %{level} %{msg}"
```

Today I realized that this options is not showed at http://www.rubydoc.info/gems/pronto/0.8.2

What am I doing wrong?? Thanks, man!!

**Comment by mmozuras** [comment]
@romulomourao this feature has not yet been released. It will be in the next version. You can use the latest version by building and installing the gem yourself (`gem build pronto.gemspec && gem install pronto-0.8.2.gem`) 😄.

Hope that answers the question, please re-open the issue if it doesn't.

**Comment by romulomourao** [comment]
Okay..I got it @mmozuras
thanks man
