### ISSUE TITLE
Use GitHub's review API to make PR comments

### ISSUE THREAD

**Issue by zhuravel** [mmozuras/pronto#217]
It is possible to make all the comments in one request and group them as one review.

Reviews API is already supported by the latest Octokit:
https://github.com/octokit/octokit.rb/releases/tag/v4.7.0
https://github.com/octokit/octokit.rb/pull/860/files

**Comment by mmozuras** [comment]
@zhuravel @doomspork @dennmart @PuercoPop which option seems better: replacing the existing `github_pr` formatter or a new one - `github_pr_review`?

**Comment by PuercoPop** [comment]
@mmozuras I'm not familiar with the code base so take my comments with a pinch of salt, but from a quick glance, having a `github_pr_review` seems better. From the base `PullRequestFormatter` it seems PRF is only concerned with submitting comments. Ideally the github_pr_review may later want also to act as a status check.

**Comment by doomspork** [comment]
@mmozuras I tend to favor a new `github_pr_review` option, I think having the choice to use one or the other would be nice to have.

**Comment by mmozuras** [comment]
Released [v0.9.0](https://github.com/mmozuras/pronto/releases/tag/v0.9.0) with `github_pr_review` as an option.

**Comment by PuercoPop** [comment]
@mmozuras thank you!

**Comment by ifokeev** [comment]
It doesn't work without header
https://github.com/mmozuras/pronto/pull/231

**Comment by zhuravel** [comment]
@mmozuras Thank you! There's one issue I've found:
Pronto tries to submit a request to GitHub even if there's no comments to submit.

This results in error message posted to console:

![pronto_zero_case](https://cloud.githubusercontent.com/assets/1140581/25526539/a25804b6-2c1c-11e7-8103-27e9cdf9ea0f.png)

**Comment by ifokeev** [comment]
@zhuravel I didn't fix this issues because I think it's OK.

**Comment by mmozuras** [comment]
Released the header fix as part of [v0.9.2](https://github.com/mmozuras/pronto/releases/tag/v0.9.2). For me it worked without the header and didn't even give a warning. Wonder why 🤔

> Pronto tries to submit a request to GitHub even if there are no comments to submit.

Could you open a new issue for it? It's a small fix, but I wouldn't wan't to forget it for next major release 😄

**Comment by zhuravel** [comment]
Done: #233
