### ISSUE TITLE
github_pr runner should not run outside the PRs

### ISSUE THREAD

**Issue by dgmora** [mmozuras/pronto#223]
Seems pretty obvious, but if you have pronto in CI with something like:
```
pronto run -c origin/master -f github_pr
```
when you run the build in `master`, you'll run into:
```
Octokit::NotFound: GET https://api.github.com/repos/dgmora/the_repo/pulls/0/comments?per_page=100: 
404 - Not Found // See: https://developer.github.com/v3
```

[this](https://github.com/mmozuras/pronto/blob/master/lib/pronto/github.rb#L70) is what is causing the issue, as it returns always 0 if there is no pull request id.

I guess the expected behaviour is that it runs nothing?

**Comment by mmozuras** [comment]
This will be improved with the upcoming release 😄. Instead of crashing with an `Octokit::NotFound`, it will error more gracefully, explaining what happened. Closing this, but please re-open if you think that it could be improved even further.

Related: https://github.com/mmozuras/pronto/issues/49.
