### ISSUE TITLE
Skip pronto for some pull requests / commits

### ISSUE THREAD

**Issue by spajus** [mmozuras/pronto#33]
Sometimes, when you are importing third party code into your repo (don't ask :smile: ), you know it will be shit and pronto will be all over it. It would be nice to be able to say `pronto no bueno` or some other safe-word in your commit message / pull request to skip pronto.

@mmozuras

**Comment by mmozuras** [comment]
@simicic @spajus you can now also specify excluded files in `.pronto.yml`. 

I've considered it, but I decided to not make the requested feature part of Pronto.
