### ISSUE TITLE
Bitbucket Formatter

### ISSUE THREAD

**Issue by johnhamelink** [mmozuras/pronto#45]
It'd be quite nice to use this with bitbucket's PR Requests!

**Comment by hron84** [comment]
I think same

**Comment by jufemaiz** [comment]
+1

**Comment by mmozuras** [comment]
Same as with #59: I'd love it and gladly merge a pull request that includes Bitbucket Formatter. But since I don't use Bitbucket myself, this is not a priority for me personally :smile:

**Comment by carlosgoce** [comment]
I was on my way to do it, I will love to have this too. But I was reading the Bitbucket's REST API documentation and I couldn't find an endpoint to send a new comment on a pull request.

I think that is not possible to do that at this time. If someone knows hows to do it...

**Comment by hron84** [comment]
@carlosgoce It is hidden in the REST API Browser.

POST https://bitbucket.org/api/1.0/repositories/{owner}/{repo-slug}/pullrequests/{id}/comments/

Required param: content

**Comment by D-system** [comment]
@carlosgoce I found that resource. Didn't work ?
https://confluence.atlassian.com/bitbucket/pullrequests-resource-1-0-296095210.html#pullrequestsResource1.0-POSTanewcomment

**Comment by MOZGIII** [comment]
:+1:

**Comment by nicka** [comment]
@carlosgoce Did you already write something? Would love to help out. Our team is using BitBucket on a day to day basis.

**Comment by mmozuras** [comment]
Merged what @nicka have done [here](https://github.com/mmozuras/pronto/pull/135). It will be the major feature of the next release :clap:
