### ISSUE TITLE
Does pronto need to have access to the entire source?

### ISSUE THREAD

**Issue by Linuus** [mmozuras/pronto#48]
Hi

Is it possible to run Pronto without checking out the entire source locally?

I mean, when commenting on a PR diff it does not seem necessary to be in the actual repo when running Pronto.

Something like this:

```
GITHUB_URL=https://github.com/mmozuras/pronto GITHUB_PR_ID=44 pronto run -f github_pr
```

This could just pull the diff from:
https://github.com/mmozuras/pronto/pull/44.diff
and analyze that?

**Comment by mmozuras** [comment]
Thought about it today and decided not to do it.

Requires changing approach too much, makes more sense as a completely separate project 😄.
