### ISSUE TITLE
Crash when there is no Github PR

### ISSUE THREAD

**Issue by Linuus** [mmozuras/pronto#49]
If I run pronto on a branch with the `github_pr` formatter it crashes if there is no PR.
`octokit-3.5.2/lib/octokit/response/raise_error.rb:16:in`on_complete': POST https://api.github.com/repos/Linuus/foobar/pulls/comments: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)`

Maybe it should just emit a more friendly message instead if the PR ID detection fails to find a PR.

**Comment by mmozuras** [comment]
@Linuus thanks for suggestion! This will be part of next release 😄
