### ISSUE TITLE
pronto misfiring on wrong commit

### ISSUE THREAD

**Issue by dankohn** [mmozuras/pronto#55]
I apologize in advance that this bug report will probably not have enough detail to enable debugging. However, last night, pronto, invoked as normal from our continuous integration machine with `bundle exec rake pronto:github` issued over 500 comments on a 5 month old commit, rather than the commit it was supposed to run on.  Specifically, my team received over 500 emails from Github with tons of specific errors, however those errors did not appear as in-line comments when I click on the accompanying link, the way they normally do.

The only thing I can find that is different is that the commit causing the problem was a revert of a commit earlier that day. However, it had nothing to do with the 5 month old commit that was being emailed about.

Unfortunately, this is a closed source project, so I don't have a good way of showing the error. And, I don't know what's causing it enough to replicate it.

But, pronto has been very reliable for me until now, so I wanted to put this out there in case others can replicate the error.

**Comment by mmozuras** [comment]
@dankohn thanks for reporting it! :+1: Never seen that before. Hope, we'll be able to get more information, random is never random :smile:

**Comment by jeroenj** [comment]
I had seen it before but it appeard to be fixed with the more recent versions of rugged.

I tracked it down to rugged using the wrong line numbers. I haven't seen the problem anymore since 0.3 was released.

@dankohn could you tell us which versions of pronto and rugged you are using?

**Comment by mmozuras** [comment]
> I had seen it before but it appeard to be fixed with the more recent versions of rugged.

Since there were no more issues of it for half a year, closing this. Unless someone will report it again, I gotta assume it was fixed with later versions of `rugged`.
