### ISSUE TITLE
Add exclude feature

### ISSUE THREAD

**Issue by hron84** [mmozuras/pronto#57]
It would be good if pronto can omit some files based on glob patterns, such as db/schema.rb in Rails project which is always a generated file and should not be a subject of any check.

**Comment by mmozuras** [comment]
@hron84 some runners already provide that possibility. For example, [pronto-rubocop](https://github.com/mmozuras/pronto-rubocop) just uses regular [.rubocop.yml](https://github.com/bbatsov/rubocop/) where you can specify exactly what you want. Does that help?

**Comment by hron84** [comment]
A bit. However, I would prefer a regular option, what can be maintained via pronto, and not directly via the underlying plugin. For example, if I exclude db/schema.rb from rubocop, it is not guarantee it will exclude from other runners. However, since the db/schema.rb is purely autogenerated, I would exclude it from **all** runners, not only from rubocop because errors reacting to this file are completelly unhelpful and unneccessary.
