### ISSUE TITLE
Gitorious Merge Request Formatter

### ISSUE THREAD

**Issue by singpolyma** [mmozuras/pronto#59]
Would be a nice integration to have.

**Comment by mmozuras** [comment]
Certainly would be. As I don't use `Gitorious` myself, this is not a priority for me. But I'd gladly merge it in if someone else wrote it :smile:

**Comment by jeroenj** [comment]
I'd say that this can be closed since Gitorious is getting shut down by the end of May: https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious/.

**Comment by mmozuras** [comment]
@jeroenj :+1:
