### ISSUE TITLE
Exit values

### ISSUE THREAD

**Issue by michaelachrisco** [mmozuras/pronto#62]
rspec, rubocop, and many other tools will run and have an exit code of 1 if anything is "wrong" with your code. 

For example: 
rubocop:
```
rubocop spec 
Inspecting 34 files
..................................

34 files inspected, no offenses detected
$ echo $?
0
```
fail
```
rubocop spec 
Inspecting 34 files
.........................C........

Offenses:

spec/mailers/batch_mailer_spec.rb:48:5: C: Use 2 (not 3) spaces for indentation.
       is_expected.to deliver_to(user.email)
    ^^^

34 files inspected, 1 offense detected
echo $?
1
```

This feature will help with integration of other tools into pronto that look at exit codes.

**Comment by michaelachrisco** [comment]
Should be as easy as a ``` Kernel.exit(1) ```

**Comment by mmozuras** [comment]
@michaelachrisco there's already `--exit-code` and no `--no-exit-code` flags that are meant for that. Do they solve your problem?

**Comment by michaelachrisco** [comment]
Yes I did not see that. Ill close this then. Thanks!
