### ISSUE TITLE
Running pronto results with segmentation fault

### ISSUE THREAD

**Issue by simicic** [mmozuras/pronto#68]
Hi!

I came across an issue that makes the pronto run task fail miserably - with **segmentation fault**. 
The error message can be seen in this gist: https://gist.github.com/simicic/60f84a1f6187c0ec6e1c

Checking it in deep I saw it comes from the **rugged** gem - I can report an issue there as well, but let me first ask, how come that a single rename of a class (class name and file name) breaks pronto? 

The task is running after the test suit on Circle CI and I could detect what actually caused the failure - or at least I like to think so. After the commit that changes the file name - things started to go wrong. 
I tried to clear the cache for running the task, update both pronto and rugged to the **latest version** but nothing seem to be helping...
(Running Ruby 2.0.0-p353, also tried with 2.1.0-p95, Pronto: 0.4.1, Rugged: 0.21.4, Github Formatter )

I would appreciate any help - maybe I am doing something wrong?

**Comment by mmozuras** [comment]
@simicic hi, thanks for reporting!

Could you create a test repository with which anyone else could reproduce it too?

**Comment by mmozuras** [comment]
@simicic maybe it's this issue: https://github.com/mmozuras/pronto/issues/103 ?

**Comment by mmozuras** [comment]
Assuming that it was #103 and closing.
