### ISSUE TITLE
Add option to use local .jshintrc file

### ISSUE THREAD

**Issue by gdumitrescu** [mmozuras/pronto#73]
Would it be possible to enable the option to run pronto-jshint against a local .jshintrc configuration 
`bundle exec pronto run --config .jshintrc`?

Thanks,
Gabriel

**Comment by mmozuras** [comment]
Sure. But I think that it would better if it would just default to that file if it exists. `pronto` itself doesn't need to be changed, just [pronto-jshint](https://github.com/mmozuras/pronto-jshint).
