### ISSUE TITLE
Review of pull-requests from everyone in an organization

### ISSUE THREAD

**Issue by fernandopso** [mmozuras/pronto#85]
Hello @mmozuras ,

I spent time getting to know the pronto gem and after some tests on pull-requests on github, I realized that the gem can analyze only my own pull-requests (please correct me if I'm wrong), but I was wondering why the gem does not apply in other pull-requests?

I think it would be very relevant if I could analyze a pull-request from another person that work in the same organization. I started writing a few lines of code to add this option and decided to take a break to get your opinion and if this feature would be a good contribution and avoid implementing a feature that would not come to be used for some reason.

https://github.com/fernandopso/pronto/commit/c5da797248659d79a5df9a4605829c9b442d018d

**Comment by mmozuras** [comment]
@fernandopso it shouldn't be limited in that way. Were you able to figure it out and subsequently closed the issue?
