### ISSUE TITLE
fasterer runner

### ISSUE THREAD

**Issue by jeroenj** [mmozuras/pronto#89]
It might be interesting to have a runner for [fasterer](https://github.com/DamirSvrtan/fasterer). I might give a shot at it but I guess you will be feaster at it. :)

**Comment by fabiosammy** [comment]
+1

**Comment by mmozuras** [comment]
Done: https://rubygems.org/gems/pronto-fasterer :smile:

**Comment by jeroenj** [comment]
Awesome, thanks. 😃

I'll add it to our list of runners. :)

**Comment by mmozuras** [comment]
@jeroenj do tell if you'll find any issues :smile:
