### ISSUE TITLE
Add "shipit" comment to github pull req if no messages were produced

### ISSUE THREAD

**Issue by johanoskarsson** [mmozuras/pronto#96]
Our workflow requires a shipit/LGTM/+1 type comment from anyone involved in a pull request. It would be handy to have pronto add such a message to the github pull request if no issues were found during the last run.

**Comment by mmozuras** [comment]
@johanoskarsson have you considered these alternatives:

* GitHub provides a [Status API](https://developer.github.com/v3/repos/statuses/). Most CI servers (like Jenkins) have plugins that make use of it. You can even have multiple builds with multiple statuses (a separate build for tests/pronto/js-tests). Pronto has an `--exit-code` option, which could be used to signal that a build has failed.
* Detecting that Pronto has returned success (again, using `--exit-code`) and running a script that would make a `shipit` comment. 

Currently, I don't feel that it makes sense to have this functionality in Pronto. Would love to hear more about your case, as I might be missing something :bow:.

**Comment by mmozuras** [comment]
Closing.

Please reopen if it's still an issue :smile: :bow:.
