### ISSUE TITLE
commit_id is not part of the pull request

### ISSUE THREAD

**Issue by johanoskarsson** [mmozuras/pronto#99]
Running pronto (installed from master at c88e2b017e011677b9f13710ccc46b99adac1329) causes the following error when using the github_pr formatter. This is reproducible and 0.4.3 of the gem does not have this behaviour. Curiously the 15609e8fb17fffbf2d51958bf5df6c57160fd281 commit sha below is not part of my local repository (git show 156... throws an error), but viewing it on github shows it as a merge of the last commit in my branch into master. Presumably that is why it fails, curious how it is picked up by pronto (or is travis ci to blame?).

bundle exec pronto run -f github_pr

Failed to post: #<struct Pronto::Github::Comment sha="15609e8fb17fffbf2d51958bf5df6c57160fd281", body="Unnecessary spacing detected.", path="file.rb", position=40> with POST https://api.github.com/repos/removed/removed/pulls/437/comments: 422 - Validation Failed
Error summary:
  resource: PullRequestReviewComment
  code: custom
  field: commit_id
  message: commit_id is not part of the pull request // See: https://developer.github.com/v3/pulls/comments/#create-a-comment
0 Pronto messages posted to GitHub

**Comment by mmozuras** [comment]
@johanoskarsson should be fixed in the next release (coming to you this month :smile:):

https://github.com/mmozuras/pronto/blob/master/CHANGELOG.md#bugs-fixed

Please reopen if it's not :bow:

**Comment by mmozuras** [comment]
@johanoskarsson did updating to the newest version help?

**Comment by johanoskarsson** [comment]
It did indeed! Thanks for the fix.
